// Requires running Vite. GETs are mocked and every POST is intercepted; no real student records.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),assert=require('assert');
const fixtures=Object.fromEntries(['inorganic','compounds','reactions','experiments'].map(type=>{
 const rows=JSON.parse(fs.readFileSync(`learning/${type}.json`));const keys=Object.keys(rows[0]);
 return [type,{csv:[keys,...rows.map(r=>keys.map(k=>r[k]??''))].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n')}];
}));
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
const make=async(handler)=>{const p=await b.newPage({viewport:{width:390,height:900}});p.setDefaultTimeout(7000);await p.clock.install();await p.addInitScript(()=>{localStorage.setItem('chem.users',JSON.stringify([{userKey:'qa-local',displayName:'確認',isPublic:false,createdAt:1}]));localStorage.setItem('chem.activeUser','qa-local')});await p.route('https://**/*',async r=>{if(r.request().method()!=='GET')return r.fulfill({status:200,body:'{}'});const u=new URL(r.request().url());let type=u.searchParams.get('type');type=type==='inorganic-new'?'inorganic':type==='experiment'?'experiments':type;await handler(r,type,u.searchParams.get('action'));});await p.goto('http://127.0.0.1:5173');return p;};
const waitForRequest=async(test)=>{for(let i=0;i<100;i++){if(test())return;await new Promise(resolve=>setTimeout(resolve,20));}throw Error('Request did not start');};
const send=(r,type)=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixtures[type]||[])});
// A failed/unneeded experiment endpoint cannot block structural questions. Successful CSV is reused.
let calls={};const p=await make((r,type)=>{calls[type]=(calls[type]||0)+1;return type==='experiments'?r.fulfill({status:503,body:'unavailable'}):send(r,type)});
await p.getByRole('button',{name:/01 \/ ORGANIC/}).click();await p.getByRole('button',{name:/^①/}).waitFor();assert.equal(calls.compounds||0,0);assert.equal(calls.experiments||0,0);
await p.getByRole('button',{name:/^①/}).click();await p.getByRole('button',{name:'10ずつ',exact:true}).waitFor();assert.equal(calls.compounds,1);assert.equal(calls.experiments||0,0);
await p.getByRole('button',{name:'10ずつ',exact:true}).click();await p.getByRole('button',{name:'1-10',exact:true}).click();await p.locator('.option-button').first().click();await p.getByText('覚えるポイント',{exact:true}).waitFor();await p.locator('.back-button').first().click();await p.locator('.question-count-selector .back-button').click();await p.getByRole('button',{name:/^②/}).click();await p.getByRole('button',{name:'10ずつ',exact:true}).waitFor();assert.equal(calls.compounds,1);console.log('INDEPENDENT_ORGANIC_AND_CACHE_PASS');await p.close();
// Simulated 16-second response: old 15-second timeout failed; new read must remain pending then render.
let slowRoute;const slow=await make((r,type)=>{if(type==='compounds'){slowRoute=r;return;}return send(r,type)});
await slow.getByRole('button',{name:/01 \/ ORGANIC/}).click();await slow.getByRole('button',{name:/^①/}).click();await slow.getByText('問題を読み込んでいます…',{exact:true}).waitFor();await waitForRequest(()=>slowRoute);await slow.clock.runFor(16000);assert.equal(await slow.locator('.status-panel [role=alert]').count(),0);await send(slowRoute,'compounds');await slow.getByRole('button',{name:'10ずつ',exact:true}).waitFor();console.log('SLOW_16_SECONDS_PASS');await slow.close();
// Missing statistics: bounded error, one shared userStats request, zero automatic retries, manual retry works.
let statsRequests=0,allowStats=false;const stats=await make((r,type,action)=>{if(action==='userStats'){statsRequests++;if(!allowStats)return;}if(action==='rec'&&!allowStats)return;return send(r,type)});
await stats.getByRole('button',{name:/01 \/ ORGANIC/}).click();await stats.getByText('公開ランキングを読み込み中…（最大45秒）',{exact:true}).waitFor();await waitForRequest(()=>statsRequests===1);await stats.clock.runFor(46000);console.log('TIMEOUT_STATE', await stats.locator('.stats-loading,.ranking-loading,.stats-error,.ranking-error').allTextContents(), statsRequests);await stats.locator('.ranking-error').waitFor();await stats.locator('.stats-error').waitFor();assert.equal(statsRequests,1);await stats.clock.runFor(60000);assert.equal(statsRequests,1);assert.equal(await stats.getByRole('button',{name:/^①/}).count(),1);for(const width of [320,844,1280]){await stats.setViewportSize({width,height:900});await stats.getByRole('group',{name:'文字の大きさ'}).getByRole('button',{name:'大',exact:true}).click();const bad=await stats.locator('.stats-error button,.ranking-error button').evaluateAll(es=>es.filter(e=>e.scrollWidth>e.clientWidth+2||e.getBoundingClientRect().right>innerWidth+2||e.getBoundingClientRect().height<44).map(e=>e.textContent));assert.deepEqual(bad,[]);}await stats.setViewportSize({width:390,height:900});await stats.screenshot({path:'/private/tmp/chemistry-loading-errors.png',fullPage:true});allowStats=true;await stats.getByRole('button',{name:'ランキングを再読み込み',exact:true}).click();await stats.getByText('まだ公開データがありません',{exact:true}).waitFor();await stats.getByRole('button',{name:'成績を再読み込み',exact:true}).click();await stats.locator('.stats-error').waitFor({state:'hidden'});console.log('STATS_TIMEOUT_DEDUP_MANUAL_RETRY_PASS');await stats.close();
// Invalid response isn't cached: explicit retry fetches the corrected dataset.
let good=false,compoundRequests=0;const invalid=await make((r,type)=>{if(type==='compounds'){compoundRequests++;if(!good)return r.fulfill({status:200,body:'{"error":"test error"}'});}return send(r,type)});
await invalid.getByRole('button',{name:/01 \/ ORGANIC/}).click();await invalid.getByRole('button',{name:/^①/}).click();await invalid.locator('.status-panel [role=alert]').waitFor();assert.equal(compoundRequests,1);good=true;await invalid.getByRole('button',{name:'再読み込み',exact:true}).click();await invalid.getByRole('button',{name:'10ずつ',exact:true}).waitFor();assert.equal(compoundRequests,2);console.log('FAILED_RESPONSE_NOT_CACHED_PASS');await invalid.close();
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
